### ISSUE TITLE
What about to stop being a fork?

### ISSUE THREAD

**Issue by zxqfox** [bem/borschik#105]
Just because:
> https://github.com/bem/borschik/search?q=woff&type=Code
> Sorry, forked repositories are not currently searchable.

Can we do something with that?

**Comment by blond** [comment]
+1

Я ещё за то, чтобы перенести все пакеты про борщик в https://github.com/borschik.

**Comment by zxqfox** [comment]
:+1:

Только enb-borschik туда не надо уносить ;-)

**Comment by blond** [comment]
> Только enb-borschik туда не надо уносить ;-)

Я и не думал =)

**Comment by arikon** [comment]
What about to stop using `borschik` at all? ;) In favor of other packages.

**Comment by alexeyten** [comment]
Like what?

**Comment by arikon** [comment]
UglifyJS for js and PostCSS with plugins (csswring etc) for css.

**Comment by alexeyten** [comment]
Uglify научился склеивать файлы?

**Comment by arikon** [comment]
@alexeyten Нет. А вы используете `borschik`, чтобы именно склеивать файлы? Мы для склеивания уже давно используем `enb`, а `borschik` использовали только для минификации и freeze.

@zxqfox делает так же, я думаю. Моё предложение перестать использовать `borschik` было адресовано ему ;)

**Comment by zxqfox** [comment]
Я даже не знал, что борщик че-то склеивать умеет ;-)

**Comment by narqo** [comment]
@arikon в «другой части компании» не используют enb и всё остальное про БЭМ.

**Comment by zxqfox** [comment]
Звучит как «обратная сторона луны», ну так что на счет открепить репозиторий? Отказ-отказом, но речь же шла про открепление сейчас, а не про планы на год.

**Comment by arikon** [comment]
@zxqfox Ты знаешь, как это сделать (я про открепление)? Кроме пересоздания его на новом месте с последующим пушем туда (потому что issues потеряются).

**Comment by zxqfox** [comment]
https://github.com/contact — суда писать надо, желательно овнерам форка.

p.s. Я вот думаю, что произойдет, если зарезать основной репо?..

**Comment by blond** [comment]
> p.s. Я вот думаю, что произойдет, если зарезать основной репо?..

Правильно думаешь ;) Делали так на ENB пакетах.

**Comment by arikon** [comment]
В прошлую мою попытку это сделать @veged был против.

**Comment by veged** [comment]
если найдётся способ всё смигрировать — я готов ради поиска пойти на это

про отказ лучше обсуждать отдельно — в ENB не все фичи повторены

**Comment by arikon** [comment]
Я написал в support просьбу сделать `bem/borschik` основным репо, а `veged/borschik` его форком.

**Comment by arikon** [comment]
Done!
