### ISSUE TITLE
Minification borschik:include

### ISSUE THREAD

**Issue by a-x-** [bem/borschik#91]
Добрый день!

Не подскажите, как делать минификацию файлов, подключаемых через `borschik:include`?

----

Hi, guys!

Could you tell me, how to minificate `borschik:include` include files?

**Comment by zxqfox** [comment]
You need minimize option as I see.
https://github.com/bem/borschik/blob/master/lib/coa.js#L74

Example of usage:
https://github.com/enb-make/enb-borschik/blob/e5a7ad2f2f57e7858586fbc3d78f9627c3d37ea1/lib/borschik-preprocessor.js#L31

**Comment by a-x-** [comment]
is it appliable for `"borschik:include"` notation?

**Comment by zxqfox** [comment]
I'm not sure but feels like yes.

/cc @tadatuta @doochik

**Comment by tadatuta** [comment]
sure

**Comment by a-x-** [comment]
Ok, thank you.
i'll try it.
